name: Test Repo Diff Logger

on:
    push:
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Install deps
              run: npm install -g pnpm && pnpm install

            - name: Run tests
              run: pnpm test -- --coverage
